### PR TITLE
Fix Stage/Progress selection

### LINKED ISSUE #13: Select not working properly
When editing a card the design stage and the progress input's are not working as expected. I can type in a value but im unable to select one. 
image

### PR DESCRIPTION
**Pull request by taysea**
`event.target.name` did not exist on the event coming from the selection. For the time being, we will pass the `name` of the FormField into the function directly. via suggestion here https://github.com/grommet/grommet-roadmap/pull/14#issuecomment-822468193

Closes #13

### CODE REVIEW

File: src/ItemEdit.js [hunk 1]
```diff
@@ -139,9 +139,17 @@ const ItemEdit = ({ index, roadmap, onChange, onDone }) => {
 
   const handleSuggestionSelect = (index, event) => {
     const values = [...dateFields];
-    if (event.target.name && event.target.name.includes('Stage')) {
+    if (
+      event.target.innerText &&
```
Comment (ericsoderberghp) [inline src/ItemEdit.js]: Any reason we cannot use `event.target.value` instead of `event.target.innerText`? Something doesn't look like typical grommet with "innerText".

File: src/ItemEdit.js [hunk 2]
```diff
@@ -139,9 +139,17 @@ const ItemEdit = ({ index, roadmap, onChange, onDone }) => {
...
+      roadmap.labels.map((label) => label.name).includes(event.target.innerText)
+    ) {
       values[index].stage = event.suggestion;
-    } else if (event.target.name && event.target.name.includes('Progress')) {
+    } else if (
+      event.target.innerText &&
+      ['Not Started', 'In Progress', 'Complete'].includes(
```
Comment (ericsoderberghp) [inline src/ItemEdit.js]: Why are we hard coding these strings? I was expecting that the caller can decide the possible states they want.

File: src/ItemEdit.js (hunk 1 above)
Comment (taysea) [reply src/ItemEdit.js]: We could just do `event.suggestion`:
```
event.suggestion &&
      roadmap.labels.map((label) => label.name).includes(event.suggestion)
```
There is no `event.target.value`

File: src/ItemEdit.js (hunk 2 above)
Comment (taysea) [reply src/ItemEdit.js]: Looping through the array of suggestions provided to the Progress select:
https://github.com/grommet/grommet-roadmap/blob/master/src/ItemEdit.js#L295

User can still type in anything they want, but selecting an item from the suggestions seems to only include these values.

File: src/ItemEdit.js (hunk 1 above)
Comment (ericsoderberghp) [reply src/ItemEdit.js]: Why did we remove the check for the name being 'Stage', to align with the property we set `.stage`?

File: src/ItemEdit.js [hunk 3]
```diff
@@ -139,9 +139,17 @@ const ItemEdit = ({ index, roadmap, onChange, onDone }) => {
 
   const handleSuggestionSelect = (index, event) => {
     const values = [...dateFields];
-    if (event.target.name && event.target.name.includes('Stage')) {
+    if (
+      event.target.innerText &&
+      roadmap.labels.map((label) => label.name).includes(event.target.innerText)
```
Comment (ericsoderberghp) [inline src/ItemEdit.js]: Why do we need this test? Can't we just check if the name is "Stage" then we set `.stage` to whatever the suggestion is?

File: src/ItemEdit.js (hunk 1 above)
Comment (taysea) [reply src/ItemEdit.js]: This is no `event.target.name` anymore. I assumed this was something that must have been changed on React's end since it was on the Synthetic Event. If it was something that grommet was adding to an event, then there may be a bug to be fixed.

File: src/ItemEdit.js (hunk 3 above)
Comment (taysea) [reply src/ItemEdit.js]: Same as above, there is no `event.target.name` on the event anymore. Maybe there is more digging to be done as to why that no longer exists on the event.

Comment (ericsoderberghp) [reply src/ItemEdit.js]: I think we want a way to reliably map the key we are setting to the field being changed.

I wonder if the `name` isn't available anymore for reasons similar to the recent Select change you made to ensure that clicking a suggestion fires an `onChange`?

Comment (taysea) [reply src/ItemEdit.js]: Yes that seems correct. The change event that comes from typing something into the input has an `event.target.name` however the event coming from a TextInput with suggestions selection does not because it's a click event.

Comment (taysea) [reply src/ItemEdit.js]: I've done some digging, this functionality with `event.target.name` worked properly until Grommet `2.16.3`, it no longer works. The reason being is that previously, when users clicked on a TextInput suggestion, the `target` of the click event was registered as the underlying `input`, which does have `name` attribute.
Screen Shot 2021-04-16 at 11 23 06 AM

However, starting in Grommet `2.16.3`, the target of that onClick event when clicking on a suggestion became the suggestion's div which does not have the `name` attribute.
Screen Shot 2021-04-16 at 11 27 41 AM

I think the question is, is this change in event.target desired/correct? Or is this a bug in grommet?

Comment (ericsoderberghp) [reply src/ItemEdit.js]: This feels like a bug in grommet. I think selecting a suggestion needs to trigger a `change` event from the underlying `<input />` DOM element in order for uncontrolled Forms to work. It would be good to verify this.

**Comment by ericsoderberghp** [comment]
For the purposes of this pull request, I would be fine passing the name of the key we are interested in in the meantime:
`const handleSuggestionSelect = (index, name, event) => {};`

**Review by ericsoderberghp — APPROVED** [review]
